name="GPG Suite"
pkgName=Install.pkg

rmName="Uninstall.app"
imgBackground="Installer/background_dmg.png"
#volumeLayout="Installer/DS_Store"


unset REVISION PRERELEASE

MAJOR=2013
MINOR=7
REVISION=31

source "$(dirname "${BASH_SOURCE[0]}")/Dependencies/GPGTools_Core/newBuildSystem/versioning.sh"
