name="GPG Suite"
pkgName=Install.pkg

rmName="Uninstall.app"
imgBackground="Installer/background_dmg.png"
#volumeLayout="Installer/DS_Store"


unset REVISION PRERELEASE


MAJOR=2014
MINOR=11
REVISION=Yosemite-
PRERELEASE=b2

source "$(dirname "${BASH_SOURCE[0]}")/Dependencies/GPGTools_Core/newBuildSystem/versioning.sh"
