name="GPGTools"

rmName="Uninstall.app"
imgBackground="Installer/background_dmg.png"
#volumeLayout="Installer/DS_Store"


unset REVISION PRERELEASE

MAJOR=2013
MINOR=07
REVISION=26

source "$(dirname "${BASH_SOURCE[0]}")/Dependencies/GPGTools_Core/newBuildSystem/versioning.sh"
